package be.leerstad.helpers.PdfGenerators;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;

import java.io.FileOutputStream;
import java.io.IOException;

public class PdfPiechartTop3 {

    private final static int top = 842;  //hoogte A4 formaat itext - rekenwaarde
    private final static int leftRightMargin = 50;


    private static final String pdfBackdrop = "results/tables/backdrop.pdf";
    private static final String piechartLocation = "src/main/resources/images/piechart.jpg";

    public static void topWaiterPieChart(String destination) throws IOException, DocumentException {
        PdfBackdrop.createPDF();
        Piechart.generatePiechart();


        PdfReader pdfReader = new PdfReader(pdfBackdrop);
        PdfStamper pdfStamper = new PdfStamper(pdfReader, new FileOutputStream(destination));

        String text = "Top 3 waiters, generated by total sales";

        PdfContentByte canvas = pdfStamper.getOverContent(1);
        ColumnText.showTextAligned(canvas, 50, new Phrase(text), leftRightMargin, top - 150, 0);

        Image image = Image.getInstance(piechartLocation);
        image.scalePercent(75);
        image.setAlignment(1);
        image.setAbsolutePosition(50 , 300);
        canvas = pdfStamper.getOverContent(1);
        canvas.addImage(image);
        pdfStamper.close();

    }
}
